### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by dshoreman** [dshoreman/albert-translate#1]
### v0.2.0
* [x] ~Set target language~ (754de1ddb7b46c2468a58e17ff5596f361bc7532)
* [x] ~Copy translated text to clipboard~ (61e933fce40736d161cb1b25ea89002057aeb169)

### v0.3.0
* [x] ~Set default target language in config~ (ee1dffc572d95edd793e02e352d7db5b70b533bc)
* [x] ~Action to open translation in Google Translate~ (8472640f791013f6e6e4486988f6cb35211bdc34)
* [x] ~Action to open config in editor when it's not set~ (fc49c09c6c346ac56230294a62e975a32f3268d3)
* [x] ~Add `code:language` map to display language names in subtext~ (c68e8ee5716f316ca045a0921e1298b05c5aceb2)

### v1.0.0
* [x] ~Set source language (for when Google gets it wrong) in query~  (a6137262f5ed398ca4c2462b82a0dc2d50022b44)
* [x] ~Support multiple comma-delimited target languages~ (2335fe8706c6fcf4a35ddb6182b378c58087295e)
* [x] ~Use lang map to check validity of language codes~ (b5de99d06ab14cade0da5bf9aa65af35aad06683)
* [x] ~Set path to service key JSON in config~ (7f2a39afc8f8197d12d677991b9d7b74601f78aa)
* [x] ~Make sure all options are added to config on startup~ (695776217e650b8cdf6dccfff84fc12c598737a1)
